### ISSUE TITLE
add news scan?

### ISSUE THREAD

**Issue by bquast** [lefranz/geneva-dictators#3]
great work!

I was wondering if it would be hard to add something like a google news scan with they keywords geneva/switzerland and a list of names of people that might be expected to be on the plane that landed.

If this does not yield any results then this could be used to say purpose of flight unknown.

**Comment by lefranz** [comment]
Thanks Baastian!

I tried with this flight we catched from Qatar on october 9:
https://twitter.com/GVA_Watcher/status/785122661567455232

and indeed, a google news search with "qatar switzerland" is bringing up this story:
http://www.trtworld.com/mea/kerry-and-lavrov-to-resume-syria-talks-in-switzerland-205746

The idea of detecting flights with "unknown purposes" is very good. The problem is that official visits tend to be reported a little while after the diplomatic flights actually land in GVA.

**Comment by bquast** [comment]
Yeah, that makes sense.

Perhaps it would be something that could be added to the tweet when the plane departs again?

In this case, the news seems to only have been released after that. In that case you perhaps think about setting it up as a follow up tweet. Something like, this/last weeks flight does not appear to have been linked to a public event.

This might even lead to some crowdsourcing in that people might reply in case they do know.
